# CA1_Machine Learning

## Import Libraries for data manipulation and analysis

Pandas - Also built on top of Python language, it is a use friendly open source toll for data manipulation and analysis. 

Numpy - Shor for Numerical Python. It's the most important foundational packages for numerical computing in Python. This library provide for example: mathematical functions, linear algebra, random number generation and so on.

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import mglearn
from cycler import cycler

In [2]:
df = pd.read_csv('cycle-counts-2022.csv')

In [3]:
df.head()

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Grove Road Totem OUT,Grove Road Totem IN,North Strand Rd N/B,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT
0,01/01/2022 00:00,0.0,0.0,0.0,0.0,0.0,0.0,6.0,4.0,2.0,...,3.0,1.0,3.0,1.0,9.0,1.0,8.0,4.0,0.0,4.0
1,01/01/2022 01:00,2.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0,1.0,...,9.0,8.0,7.0,5.0,6.0,0.0,6.0,1.0,0.0,1.0
2,01/01/2022 02:00,0.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,4.0,...,7.0,0.0,2.0,3.0,9.0,0.0,9.0,6.0,0.0,6.0
3,01/01/2022 03:00,1.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,...,5.0,4.0,5.0,0.0,6.0,0.0,6.0,2.0,0.0,2.0
4,01/01/2022 04:00,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,4.0,5.0,2.0,1.0,2.0,0.0,2.0,0.0,0.0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 33 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Time                                         8760 non-null   object
 1   Charleville Mall                             8751 non-null   float64
 2   Charleville Mall Cyclist IN                  8751 non-null   float64
 3   Charleville Mall Cyclist OUT                 8751 non-null   float64
 4   Clontarf - James Larkin Rd                   8759 non-null   float64
 5   Clontarf - James Larkin Rd Cyclist IN        8759 non-null   float64
 6   Clontarf - James Larkin Rd Cyclist OUT       8759 non-null   float64
 7   Clontarf - Pebble Beach Carpark              8759 non-null   float64
 8   Clontarf - Pebble Beach Carpark Cyclist IN   8759 non-null   float64
 9   Clontarf - Pebble Beach Carpark Cyclist OUT  8759 non-null   float64
 10  Drumcondra Cyclists 1                        8759 non-null   float64
 11  Drumcondra Cyclists 1 Cyclist IN             8759 non-null   float64
 12  Drumcondra Cyclists 1 Cyclist OUT            8759 non-null   float64
 13  Drumcondra Cyclists 2                        8759 non-null   float64
 14  Drumcondra Cyclists 2 Cyclist IN             8759 non-null   float64
 15  Drumcondra Cyclists 2 Cyclist OUT            8759 non-null   float64
 16  Griffith Avenue (Clare Rd Side)              8752 non-null   float64
 17  Griffith Avenue (Clare Rd Side) Cyclist IN   8752 non-null   float64
 18  Griffith Avenue (Clare Rd Side) Cyclist OUT  8752 non-null   float64
 19  Griffith Avenue (Lane Side)                  8748 non-null   float64
 20  Griffith Avenue (Lane Side) Cyclist IN       8748 non-null   float64
 21  Griffith Avenue (Lane Side) Cyclist OUT      8748 non-null   float64
 22  Grove Road Totem                             8759 non-null   float64
 23  Grove Road Totem OUT                         8759 non-null   float64
 24  Grove Road Totem IN                          8759 non-null   float64
 25  North Strand Rd N/B                          8751 non-null   float64
 26  North Strand Rd S/B                          2991 non-null   float64
 27  Richmond Street Cyclists 1                   8759 non-null   float64
 28  Richmond Street Cyclists 1 Cyclist IN        8759 non-null   float64
 29  Richmond Street Cyclists 1 Cyclist OUT       8759 non-null   float64
 30  Richmond Street Cyclists 2                   8759 non-null   float64
 31  Richmond Street Cyclists 2  Cyclist IN       8759 non-null   float64
 32  Richmond Street Cyclists 2  Cyclist OUT      8759 non-null   float64
dtypes: float64(32), object(1)
memory usage: 2.2+ MB

In [5]:
# Transform dtype object to datetime dtype. 
df['Time'] = pd.to_datetime(df['Time'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 33 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Time                                         8760 non-null   datetime64[ns]
 1   Charleville Mall                             8751 non-null   float64
 2   Charleville Mall Cyclist IN                  8751 non-null   float64
 3   Charleville Mall Cyclist OUT                 8751 non-null   float64
 4   Clontarf - James Larkin Rd                   8759 non-null   float64
 5   Clontarf - James Larkin Rd Cyclist IN        8759 non-null   float64
 6   Clontarf - James Larkin Rd Cyclist OUT       8759 non-null   float64
 7   Clontarf - Pebble Beach Carpark              8759 non-null   float64
 8   Clontarf - Pebble Beach Carpark Cyclist IN   8759 non-null   float64
 9   Clontarf - Pebble Beach Carpark Cyclist OUT  8759 non-null   float64
 10  Drumcondra Cyclists 1                        8759 non-null   float64
 11  Drumcondra Cyclists 1 Cyclist IN             8759 non-null   float64
 12  Drumcondra Cyclists 1 Cyclist OUT            8759 non-null   float64
 13  Drumcondra Cyclists 2                        8759 non-null   float64
 14  Drumcondra Cyclists 2 Cyclist IN             8759 non-null   float64
 15  Drumcondra Cyclists 2 Cyclist OUT            8759 non-null   float64
 16  Griffith Avenue (Clare Rd Side)              8752 non-null   float64
 17  Griffith Avenue (Clare Rd Side) Cyclist IN   8752 non-null   float64
 18  Griffith Avenue (Clare Rd Side) Cyclist OUT  8752 non-null   float64
 19  Griffith Avenue (Lane Side)                  8748 non-null   float64
 20  Griffith Avenue (Lane Side) Cyclist IN       8748 non-null   float64
 21  Griffith Avenue (Lane Side) Cyclist OUT      8748 non-null   float64
 22  Grove Road Totem                             8759 non-null   float64
 23  Grove Road Totem OUT                         8759 non-null   float64
 24  Grove Road Totem IN                          8759 non-null   float64
 25  North Strand Rd N/B                          8751 non-null   float64
 26  North Strand Rd S/B                          2991 non-null   float64
 27  Richmond Street Cyclists 1                   8759 non-null   float64
 28  Richmond Street Cyclists 1 Cyclist IN        8759 non-null   float64
 29  Richmond Street Cyclists 1 Cyclist OUT       8759 non-null   float64
 30  Richmond Street Cyclists 2                   8759 non-null   float64
 31  Richmond Street Cyclists 2  Cyclist IN       8759 non-null   float64
 32  Richmond Street Cyclists 2  Cyclist OUT      8759 non-null   float64
dtypes: datetime64[ns](1), float64(32)
memory usage: 2.2 MB

In [6]:
df['Cycle_year'] = df['Time'].dt.year
df.sample(5)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Grove Road Totem IN,North Strand Rd N/B,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year
915,2022-08-02 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022
5643,2022-08-24 03:00:00,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,NaN,7.0,0.0,7.0,3.0,0.0,3.0,2022
5137,2022-03-08 01:00:00,1.0,0.0,1.0,6.0,4.0,2.0,3.0,1.0,2.0,...,0.0,0.0,NaN,2.0,0.0,2.0,0.0,0.0,0.0,2022
6581,2022-02-10 05:00:00,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3.0,0.0,NaN,5.0,0.0,5.0,6.0,0.0,6.0,2022
2509,2022-04-15 13:00:00,20.0,12.0,8.0,88.0,41.0,47.0,130.0,61.0,69.0,...,74.0,77.0,47.0,104.0,0.0,104.0,121.0,1.0,120.0,2022

In [7]:
## To extract month from the date you use dt.month method and create new column with months

df['Cycle_Month_No'] = df['Time'].dt.month
df.sample(5)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,North Strand Rd N/B,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No
2937,2022-03-05 09:00:00,35.0,31.0,4.0,55.0,39.0,16.0,63.0,46.0,17.0,...,26.0,163.0,30.0,0.0,30.0,139.0,0.0,139.0,2022,3
7456,2022-07-11 16:00:00,28.0,15.0,13.0,35.0,11.0,24.0,43.0,11.0,32.0,...,0.0,NaN,114.0,0.0,114.0,81.0,0.0,81.0,2022,7
1675,2022-11-03 19:00:00,11.0,2.0,9.0,15.0,6.0,9.0,25.0,6.0,19.0,...,74.0,30.0,117.0,0.0,117.0,81.0,1.0,80.0,2022,11
1609,2022-09-03 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,1.0,2.0,0.0,2.0,0.0,0.0,0.0,2022,9
4938,2022-07-25 18:00:00,53.0,16.0,37.0,114.0,43.0,71.0,150.0,49.0,101.0,...,199.0,NaN,209.0,2.0,207.0,136.0,1.0,135.0,2022,7

In [8]:
df['Cycle_Month'] = df['Time'].dt.month_name()
df.sample(5)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month
98,2022-05-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,5,May
99,2022-05-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,3.0,0.0,3.0,0.0,0.0,0.0,2022,5,May
2418,2022-11-04 18:00:00,36.0,14.0,22.0,64.0,16.0,48.0,89.0,25.0,64.0,...,37.0,186.0,0.0,186.0,117.0,1.0,116.0,2022,11,November
737,2022-01-31 17:00:00,31.0,10.0,21.0,54.0,17.0,37.0,66.0,12.0,54.0,...,48.0,162.0,0.0,162.0,98.0,0.0,98.0,2022,1,January
3218,2022-05-15 02:00:00,0.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,...,NaN,20.0,1.0,19.0,8.0,0.0,8.0,2022,5,May

In [9]:
## To extract day from the date you use dt.day method and create new column with day
df['Cycle_Day'] = df['Time'].dt.day
df.sample(5)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month,Cycle_Day
2163,2022-01-04 03:00:00,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,5.0,0.0,5.0,3.0,0.0,3.0,2022,1,January,4
3202,2022-05-14 10:00:00,14.0,8.0,6.0,199.0,88.0,111.0,233.0,93.0,140.0,...,38.0,0.0,38.0,95.0,0.0,95.0,2022,5,May,14
7747,2022-11-19 19:00:00,5.0,3.0,2.0,5.0,2.0,3.0,10.0,2.0,8.0,...,90.0,1.0,89.0,37.0,0.0,37.0,2022,11,November,19
1976,2022-03-24 08:00:00,83.0,74.0,9.0,81.0,59.0,22.0,109.0,78.0,31.0,...,85.0,0.0,85.0,199.0,3.0,196.0,2022,3,March,24
6363,2022-09-23 03:00:00,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,8.0,0.0,8.0,3.0,0.0,3.0,2022,9,September,23

In [10]:
## To extract day of the week from the date you use dt.day_name method and create new column with day of the week
df['Cycle_Dayofweek'] = df['Time'].dt.day_name()
df.sample(5)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month,Cycle_Day,Cycle_Dayofweek
7723,2022-11-18 19:00:00,15.0,5.0,10.0,21.0,7.0,14.0,26.0,6.0,20.0,...,0.0,119.0,101.0,0.0,101.0,2022,11,November,18,Friday
1780,2022-03-16 04:00:00,0.0,0.0,0.0,3.0,2.0,1.0,3.0,2.0,1.0,...,0.0,0.0,2.0,0.0,2.0,2022,3,March,16,Wednesday
4132,2022-06-22 04:00:00,2.0,1.0,1.0,3.0,3.0,0.0,6.0,4.0,2.0,...,0.0,1.0,2.0,0.0,2.0,2022,6,June,22,Wednesday
7985,2022-11-29 17:00:00,72.0,20.0,52.0,90.0,20.0,70.0,129.0,26.0,103.0,...,2.0,267.0,122.0,0.0,122.0,2022,11,November,29,Tuesday
4411,2022-03-07 19:00:00,10.0,5.0,5.0,64.0,33.0,31.0,70.0,38.0,32.0,...,1.0,78.0,103.0,0.0,103.0,2022,3,March,7,Monday

In [11]:
df['Cycle_Dayofweek'].replace('Monday', 1, inplace=True)
df['Cycle_Dayofweek'].replace('Tuesday', 2, inplace=True)
df['Cycle_Dayofweek'].replace('Wednesday',3, inplace=True)
df['Cycle_Dayofweek'].replace('Thursday', 4, inplace=True)
df['Cycle_Dayofweek'].replace('Friday', 5, inplace=True)
df['Cycle_Dayofweek'].replace('Saturday', 6, inplace=True)
df['Cycle_Dayofweek'].replace('Sunday', 7, inplace=True)

In [12]:
df.sample(10)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month,Cycle_Day,Cycle_Dayofweek
4402,2022-03-07 10:00:00,10.0,6.0,4.0,156.0,65.0,91.0,157.0,57.0,100.0,...,0.0,26.0,49.0,0.0,49.0,2022,3,March,7,1
8686,2022-12-28 22:00:00,6.0,4.0,2.0,2.0,2.0,0.0,5.0,3.0,2.0,...,0.0,22.0,24.0,0.0,24.0,2022,12,December,28,3
2759,2022-04-25 23:00:00,1.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,...,0.0,26.0,13.0,0.0,13.0,2022,4,April,25,1
6693,2022-06-10 21:00:00,13.0,2.0,11.0,10.0,4.0,6.0,20.0,4.0,16.0,...,1.0,113.0,69.0,2.0,67.0,2022,6,June,10,5
5663,2022-08-24 23:00:00,5.0,1.0,4.0,8.0,4.0,4.0,9.0,2.0,7.0,...,0.0,44.0,29.0,0.0,29.0,2022,8,August,24,3
5137,2022-03-08 01:00:00,1.0,0.0,1.0,6.0,4.0,2.0,3.0,1.0,2.0,...,0.0,2.0,0.0,0.0,0.0,2022,3,March,8,2
1191,2022-02-19 15:00:00,11.0,4.0,7.0,57.0,22.0,35.0,61.0,22.0,39.0,...,0.0,64.0,98.0,0.0,98.0,2022,2,February,19,6
150,2022-07-01 06:00:00,9.0,8.0,1.0,10.0,8.0,2.0,14.0,11.0,3.0,...,0.0,7.0,16.0,0.0,16.0,2022,7,July,1,5
6762,2022-09-10 18:00:00,4.0,1.0,3.0,18.0,9.0,9.0,25.0,11.0,14.0,...,0.0,84.0,81.0,1.0,80.0,2022,9,September,10,6
3241,2022-05-16 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,1.0,0.0,1.0,2022,5,May,16,1

In [13]:
## To extrat if cyclists are cycling on Saturday or Sunday 
df['Cycle_On_Weekend'] = np.where(df['Cycle_Dayofweek'].isin(['Sunday','Saturday']), 1,0 )
df.sample(10)

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month,Cycle_Day,Cycle_Dayofweek,Cycle_On_Weekend
2736,2022-04-25 00:00:00,1.0,1.0,0.0,2.0,1.0,1.0,2.0,1.0,1.0,...,11.0,12.0,0.0,12.0,2022,4,April,25,1,0
2022,2022-03-26 06:00:00,0.0,0.0,0.0,7.0,3.0,4.0,16.0,4.0,12.0,...,15.0,18.0,0.0,18.0,2022,3,March,26,6,0
4067,2022-06-19 11:00:00,7.0,4.0,3.0,174.0,90.0,84.0,203.0,104.0,99.0,...,43.0,55.0,0.0,55.0,2022,6,June,19,7,0
2328,2022-08-04 00:00:00,3.0,1.0,2.0,2.0,2.0,0.0,3.0,2.0,1.0,...,43.0,20.0,0.0,20.0,2022,8,August,4,4,0
3774,2022-07-06 06:00:00,21.0,18.0,3.0,29.0,20.0,9.0,35.0,26.0,9.0,...,15.0,46.0,0.0,46.0,2022,7,July,6,3,0
2772,2022-04-26 12:00:00,8.0,5.0,3.0,61.0,32.0,29.0,67.0,30.0,37.0,...,71.0,103.0,1.0,102.0,2022,4,April,26,2,0
1076,2022-02-14 20:00:00,8.0,2.0,6.0,23.0,7.0,16.0,32.0,11.0,21.0,...,125.0,78.0,0.0,78.0,2022,2,February,14,1,0
6206,2022-09-16 14:00:00,20.0,9.0,11.0,60.0,28.0,32.0,76.0,31.0,45.0,...,84.0,104.0,0.0,104.0,2022,9,September,16,5,0
4271,2022-06-27 23:00:00,2.0,0.0,2.0,6.0,2.0,4.0,11.0,5.0,6.0,...,38.0,19.0,0.0,19.0,2022,6,June,27,1,0
464,2022-01-20 08:00:00,53.0,41.0,12.0,72.0,52.0,20.0,83.0,56.0,27.0,...,36.0,82.0,0.0,82.0,2022,1,January,20,4,0

In [14]:
df['Hour'] = df['Time'].dt.time
df.head()

,Time,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,...,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_year,Cycle_Month_No,Cycle_Month,Cycle_Day,Cycle_Dayofweek,Cycle_On_Weekend,Hour
0,2022-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,6.0,4.0,2.0,...,4.0,0.0,4.0,2022,1,January,1,6,0,00:00:00
1,2022-01-01 01:00:00,2.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,2022,1,January,1,6,0,01:00:00
2,2022-01-01 02:00:00,0.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,4.0,...,6.0,0.0,6.0,2022,1,January,1,6,0,02:00:00
3,2022-01-01 03:00:00,1.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,...,2.0,0.0,2.0,2022,1,January,1,6,0,03:00:00
4,2022-01-01 04:00:00,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,2022,1,January,1,6,0,04:00:00

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 40 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Time                                         8760 non-null   datetime64[ns]
 1   Charleville Mall                             8751 non-null   float64
 2   Charleville Mall Cyclist IN                  8751 non-null   float64
 3   Charleville Mall Cyclist OUT                 8751 non-null   float64
 4   Clontarf - James Larkin Rd                   8759 non-null   float64
 5   Clontarf - James Larkin Rd Cyclist IN        8759 non-null   float64
 6   Clontarf - James Larkin Rd Cyclist OUT       8759 non-null   float64
 7   Clontarf - Pebble Beach Carpark              8759 non-null   float64
 8   Clontarf - Pebble Beach Carpark Cyclist IN   8759 non-null   float64
 9   Clontarf - Pebble Beach Carpark Cyclist OUT  8759 non-null   float64
 10  Drumcondra Cyclists 1                        8759 non-null   float64
 11  Drumcondra Cyclists 1 Cyclist IN             8759 non-null   float64
 12  Drumcondra Cyclists 1 Cyclist OUT            8759 non-null   float64
 13  Drumcondra Cyclists 2                        8759 non-null   float64
 14  Drumcondra Cyclists 2 Cyclist IN             8759 non-null   float64
 15  Drumcondra Cyclists 2 Cyclist OUT            8759 non-null   float64
 16  Griffith Avenue (Clare Rd Side)              8752 non-null   float64
 17  Griffith Avenue (Clare Rd Side) Cyclist IN   8752 non-null   float64
 18  Griffith Avenue (Clare Rd Side) Cyclist OUT  8752 non-null   float64
 19  Griffith Avenue (Lane Side)                  8748 non-null   float64
 20  Griffith Avenue (Lane Side) Cyclist IN       8748 non-null   float64
 21  Griffith Avenue (Lane Side) Cyclist OUT      8748 non-null   float64
 22  Grove Road Totem                             8759 non-null   float64
 23  Grove Road Totem OUT                         8759 non-null   float64
 24  Grove Road Totem IN                          8759 non-null   float64
 25  North Strand Rd N/B                          8751 non-null   float64
 26  North Strand Rd S/B                          2991 non-null   float64
 27  Richmond Street Cyclists 1                   8759 non-null   float64
 28  Richmond Street Cyclists 1 Cyclist IN        8759 non-null   float64
 29  Richmond Street Cyclists 1 Cyclist OUT       8759 non-null   float64
 30  Richmond Street Cyclists 2                   8759 non-null   float64
 31  Richmond Street Cyclists 2  Cyclist IN       8759 non-null   float64
 32  Richmond Street Cyclists 2  Cyclist OUT      8759 non-null   float64
 33  Cycle_year                                   8760 non-null   int64
 34  Cycle_Month_No                               8760 non-null   int64
 35  Cycle_Month                                  8760 non-null   object
 36  Cycle_Day                                    8760 non-null   int64
 37  Cycle_Dayofweek                              8760 non-null   int64
 38  Cycle_On_Weekend                             8760 non-null   int32
 39  Hour                                         8760 non-null   object
dtypes: datetime64[ns](1), float64(32), int32(1), int64(4), object(2)
memory usage: 2.6+ MB

In [16]:
new = df.drop(columns=['Time', 'Cycle_Month', 'Cycle_Day', 'Hour', 'Cycle_year', 'Cycle_Month_No','Cycle_On_Weekend' ])
new.head()

,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,Drumcondra Cyclists 1,...,Grove Road Totem IN,North Strand Rd N/B,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_Dayofweek
0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,4.0,2.0,0.0,...,1.0,3.0,1.0,9.0,1.0,8.0,4.0,0.0,4.0,6
1,2.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,...,8.0,7.0,5.0,6.0,0.0,6.0,1.0,0.0,1.0,6
2,0.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,4.0,0.0,...,0.0,2.0,3.0,9.0,0.0,9.0,6.0,0.0,6.0,6
3,1.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,0.0,...,4.0,5.0,0.0,6.0,0.0,6.0,2.0,0.0,2.0,6
4,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,5.0,2.0,1.0,2.0,0.0,2.0,0.0,0.0,0.0,6

In [17]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 33 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Charleville Mall                             8751 non-null   float64
 1   Charleville Mall Cyclist IN                  8751 non-null   float64
 2   Charleville Mall Cyclist OUT                 8751 non-null   float64
 3   Clontarf - James Larkin Rd                   8759 non-null   float64
 4   Clontarf - James Larkin Rd Cyclist IN        8759 non-null   float64
 5   Clontarf - James Larkin Rd Cyclist OUT       8759 non-null   float64
 6   Clontarf - Pebble Beach Carpark              8759 non-null   float64
 7   Clontarf - Pebble Beach Carpark Cyclist IN   8759 non-null   float64
 8   Clontarf - Pebble Beach Carpark Cyclist OUT  8759 non-null   float64
 9   Drumcondra Cyclists 1                        8759 non-null   float64
 10  Drumcondra Cyclists 1 Cyclist IN             8759 non-null   float64
 11  Drumcondra Cyclists 1 Cyclist OUT            8759 non-null   float64
 12  Drumcondra Cyclists 2                        8759 non-null   float64
 13  Drumcondra Cyclists 2 Cyclist IN             8759 non-null   float64
 14  Drumcondra Cyclists 2 Cyclist OUT            8759 non-null   float64
 15  Griffith Avenue (Clare Rd Side)              8752 non-null   float64
 16  Griffith Avenue (Clare Rd Side) Cyclist IN   8752 non-null   float64
 17  Griffith Avenue (Clare Rd Side) Cyclist OUT  8752 non-null   float64
 18  Griffith Avenue (Lane Side)                  8748 non-null   float64
 19  Griffith Avenue (Lane Side) Cyclist IN       8748 non-null   float64
 20  Griffith Avenue (Lane Side) Cyclist OUT      8748 non-null   float64
 21  Grove Road Totem                             8759 non-null   float64
 22  Grove Road Totem OUT                         8759 non-null   float64
 23  Grove Road Totem IN                          8759 non-null   float64
 24  North Strand Rd N/B                          8751 non-null   float64
 25  North Strand Rd S/B                          2991 non-null   float64
 26  Richmond Street Cyclists 1                   8759 non-null   float64
 27  Richmond Street Cyclists 1 Cyclist IN        8759 non-null   float64
 28  Richmond Street Cyclists 1 Cyclist OUT       8759 non-null   float64
 29  Richmond Street Cyclists 2                   8759 non-null   float64
 30  Richmond Street Cyclists 2  Cyclist IN       8759 non-null   float64
 31  Richmond Street Cyclists 2  Cyclist OUT      8759 non-null   float64
 32  Cycle_Dayofweek                              8760 non-null   int64
dtypes: float64(32), int64(1)
memory usage: 2.2 MB

## Statistics Summary

In [18]:
new.describe()

,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,Drumcondra Cyclists 1,...,Grove Road Totem IN,North Strand Rd N/B,North Strand Rd S/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_Dayofweek
count,8751.000000,8751.000000,8751.000000,8759.000000,8759.000000,8759.000000,8759.000000,8759.000000,8759.000000,8759.0,...,8759.000000,8751.000000,2991.000000,8759.000000,8759.000000,8759.000000,8759.000000,8759.000000,8759.000000,8760.000000
mean,14.991544,9.006856,5.984687,38.985957,19.083914,19.902044,50.607718,23.513301,27.094417,0.0,...,61.953191,25.945835,35.047810,52.351638,0.312250,52.039388,57.615824,0.277886,57.337938,4.005479
std,18.625670,14.389145,8.360505,43.723920,21.906477,24.270776,56.794005,27.714568,32.610311,0.0,...,76.713317,45.508221,43.356592,50.514244,0.607951,50.320284,46.336813,0.565389,46.167630,2.000107
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,1.000000,1.000000,4.000000,2.000000,2.000000,5.000000,2.000000,3.000000,0.0,...,11.000000,0.000000,6.000000,11.000000,0.000000,11.000000,11.000000,0.000000,11.000000,2.000000
50%,10.000000,5.000000,4.000000,24.000000,11.000000,11.000000,32.000000,14.000000,16.000000,0.0,...,48.000000,5.000000,26.000000,40.000000,0.000000,39.000000,58.000000,0.000000,58.000000,4.000000
75%,19.000000,11.000000,8.000000,61.000000,29.000000,30.000000,77.000000,35.000000,39.000000,0.0,...,77.000000,36.000000,45.000000,77.000000,0.000000,76.000000,90.000000,0.000000,89.000000,6.000000
max,176.000000,151.000000,69.000000,319.000000,168.000000,172.000000,399.000000,195.000000,243.000000,0.0,...,658.000000,371.000000,363.000000,300.000000,5.000000,299.000000,289.000000,4.000000,289.000000,7.000000

## Checking out Duplicated data

In [19]:
new.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8755    False
8756    False
8757    False
8758    False
8759    False
Length: 8760, dtype: bool

## Filtering missing data

In [20]:
new.isnull().sum()

Charleville Mall                                  9
Charleville Mall Cyclist IN                       9
Charleville Mall Cyclist OUT                      9
Clontarf - James Larkin Rd                        1
Clontarf - James Larkin Rd Cyclist IN             1
Clontarf - James Larkin Rd Cyclist OUT            1
Clontarf - Pebble Beach Carpark                   1
Clontarf - Pebble Beach Carpark Cyclist IN        1
Clontarf - Pebble Beach Carpark Cyclist OUT       1
Drumcondra Cyclists 1                             1
Drumcondra Cyclists 1 Cyclist IN                  1
Drumcondra Cyclists 1 Cyclist OUT                 1
Drumcondra Cyclists 2                             1
Drumcondra Cyclists 2 Cyclist IN                  1
Drumcondra Cyclists 2 Cyclist OUT                 1
Griffith Avenue (Clare Rd Side)                   8
Griffith Avenue (Clare Rd Side) Cyclist IN        8
Griffith Avenue (Clare Rd Side) Cyclist OUT       8
Griffith Avenue (Lane Side)                      12
Griffith Avenue (Lane Side) Cyclist IN           12
Griffith Avenue (Lane Side) Cyclist OUT          12
Grove Road Totem                                  1
Grove Road Totem OUT                              1
Grove Road Totem IN                               1
North Strand Rd N/B                               9
North Strand Rd S/B                            5769
Richmond Street Cyclists 1                        1
Richmond Street Cyclists 1 Cyclist IN             1
Richmond Street Cyclists 1 Cyclist OUT            1
Richmond Street Cyclists 2                        1
Richmond Street Cyclists 2  Cyclist IN            1
Richmond Street Cyclists 2  Cyclist OUT           1
Cycle_Dayofweek                                   0
dtype: int64

### Dropping colum: ('North Strand RD S/B') as it has 5769 missing data

In [21]:
new.drop(columns=['North Strand Rd S/B'], inplace=True)
new.head()

,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,Drumcondra Cyclists 1,...,Grove Road Totem OUT,Grove Road Totem IN,North Strand Rd N/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_Dayofweek
0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,4.0,2.0,0.0,...,3.0,1.0,3.0,9.0,1.0,8.0,4.0,0.0,4.0,6
1,2.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,...,9.0,8.0,7.0,6.0,0.0,6.0,1.0,0.0,1.0,6
2,0.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,4.0,0.0,...,7.0,0.0,2.0,9.0,0.0,9.0,6.0,0.0,6.0,6
3,1.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,0.0,...,5.0,4.0,5.0,6.0,0.0,6.0,2.0,0.0,2.0,6
4,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,4.0,5.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,6

### In order to deal with the missing data I have used the method fillna (0). I believe that would be a good approach for this dataset as opposed to drop all the missing values.

In [22]:
new.fillna(0, inplace=True)
new.isnull().sum()

Charleville Mall                               0
Charleville Mall Cyclist IN                    0
Charleville Mall Cyclist OUT                   0
Clontarf - James Larkin Rd                     0
Clontarf - James Larkin Rd Cyclist IN          0
Clontarf - James Larkin Rd Cyclist OUT         0
Clontarf - Pebble Beach Carpark                0
Clontarf - Pebble Beach Carpark Cyclist IN     0
Clontarf - Pebble Beach Carpark Cyclist OUT    0
Drumcondra Cyclists 1                          0
Drumcondra Cyclists 1 Cyclist IN               0
Drumcondra Cyclists 1 Cyclist OUT              0
Drumcondra Cyclists 2                          0
Drumcondra Cyclists 2 Cyclist IN               0
Drumcondra Cyclists 2 Cyclist OUT              0
Griffith Avenue (Clare Rd Side)                0
Griffith Avenue (Clare Rd Side) Cyclist IN     0
Griffith Avenue (Clare Rd Side) Cyclist OUT    0
Griffith Avenue (Lane Side)                    0
Griffith Avenue (Lane Side) Cyclist IN         0
Griffith Avenue (Lane Side) Cyclist OUT        0
Grove Road Totem                               0
Grove Road Totem OUT                           0
Grove Road Totem IN                            0
North Strand Rd N/B                            0
Richmond Street Cyclists 1                     0
Richmond Street Cyclists 1 Cyclist IN          0
Richmond Street Cyclists 1 Cyclist OUT         0
Richmond Street Cyclists 2                     0
Richmond Street Cyclists 2  Cyclist IN         0
Richmond Street Cyclists 2  Cyclist OUT        0
Cycle_Dayofweek                                0
dtype: int64

In [23]:
new.sample(10)

,Charleville Mall,Charleville Mall Cyclist IN,Charleville Mall Cyclist OUT,Clontarf - James Larkin Rd,Clontarf - James Larkin Rd Cyclist IN,Clontarf - James Larkin Rd Cyclist OUT,Clontarf - Pebble Beach Carpark,Clontarf - Pebble Beach Carpark Cyclist IN,Clontarf - Pebble Beach Carpark Cyclist OUT,Drumcondra Cyclists 1,...,Grove Road Totem OUT,Grove Road Totem IN,North Strand Rd N/B,Richmond Street Cyclists 1,Richmond Street Cyclists 1 Cyclist IN,Richmond Street Cyclists 1 Cyclist OUT,Richmond Street Cyclists 2,Richmond Street Cyclists 2 Cyclist IN,Richmond Street Cyclists 2 Cyclist OUT,Cycle_Dayofweek
3713,12.0,6.0,6.0,64.0,31.0,33.0,88.0,41.0,47.0,0.0,...,42.0,39.0,49.0,91.0,0.0,91.0,86.0,1.0,85.0,3
8684,6.0,2.0,4.0,3.0,1.0,2.0,6.0,4.0,2.0,0.0,...,16.0,21.0,0.0,44.0,0.0,44.0,43.0,0.0,43.0,3
3521,38.0,11.0,27.0,122.0,46.0,76.0,160.0,59.0,101.0,0.0,...,159.0,124.0,200.0,202.0,0.0,202.0,141.0,0.0,141.0,5
7458,37.0,16.0,21.0,53.0,10.0,43.0,65.0,6.0,59.0,0.0,...,181.0,101.0,0.0,186.0,0.0,186.0,83.0,0.0,83.0,1
8474,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,2.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,1.0,2
6403,12.0,7.0,5.0,40.0,15.0,25.0,49.0,24.0,25.0,0.0,...,43.0,60.0,0.0,31.0,0.0,31.0,92.0,0.0,92.0,6
4934,21.0,8.0,13.0,32.0,11.0,21.0,42.0,21.0,21.0,0.0,...,41.0,55.0,56.0,68.0,2.0,66.0,65.0,1.0,64.0,1
2036,10.0,6.0,4.0,8.0,6.0,2.0,44.0,24.0,20.0,0.0,...,64.0,89.0,49.0,91.0,0.0,91.0,97.0,0.0,97.0,6
3980,22.0,6.0,16.0,94.0,47.0,47.0,115.0,61.0,54.0,0.0,...,93.0,64.0,86.0,103.0,1.0,102.0,107.0,0.0,107.0,3
6951,20.0,10.0,10.0,13.0,1.0,12.0,30.0,8.0,22.0,0.0,...,85.0,54.0,0.0,84.0,0.0,84.0,64.0,0.0,64.0,1

In [24]:
pip install joblib

Requirement already satisfied: joblib in c:\users\lenovo\anaconda3\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
pip install mglearn

Requirement already satisfied: mglearn in c:\users\lenovo\anaconda3\lib\site-packages (0.2.0)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (1.24.3)
Requirement already satisfied: matplotlib in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (3.7.1)
Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (1.3.0)
Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (1.5.3)
Requirement already satisfied: pillow in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (9.4.0)
Requirement already satisfied: cycler in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (0.11.0)
Requirement already satisfied: imageio in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (2.26.0)
Requirement already satisfied: joblib in c:\users\lenovo\anaconda3\lib\site-packages (from mglearn) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (1.0.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib->mglearn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas->mglearn) (2022.7)
Requirement already satisfied: scipy>=1.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn->mglearn) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn->mglearn) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->mglearn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
# Features of my dataset
X = new.iloc[:,:31]

# Store the target variable as lable into an array y
y = new.iloc[:,31]

# Display number of rows and columns
X.shape, y.shape

((8760, 31), (8760,))

In [27]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

X.shape, y.shape, X_train.shape, X_test.shape, y_train.shape, y_test.shape
# 0.2 means 20% for testing and random_state simply sets a seed to the random generator, so that your train-test splits
# are always deterministic. If we don't set a seed, it is different each time.

((8760, 31), (8760,), (7008, 31), (1752, 31), (7008,), (1752,))

In [28]:
from sklearn.preprocessing import StandardScaler   #We scale the data in order to calculate the correct distance between datapoints. 

# Create an object using Standard scalscaler
scaler = StandardScaler()

# Train the StandardScaler model
scaler.fit(X_train)

# transform data
X_train_scaled = scaler.transform(X_train)
X_test_scaled  = scaler.transform(X_test)
X_scaled = scaler.transform(X)

# print dataset after scaling
print(X_train_scaled, '\t', X_test_scaled, '\t', X_scaled)

[[ 1.09587944e-01  4.19513048e-01 -4.77232388e-01 ... -5.74688317e-01
  -4.92595634e-01 -5.70708719e-01]
 [-8.01498541e-01 -6.22430332e-01 -7.16172488e-01 ... -1.22158652e+00
  -4.92595634e-01 -1.21997551e+00]
 [-7.47905218e-01 -6.22430332e-01 -5.96702438e-01 ... -1.15689670e+00
  -4.92595634e-01 -1.15504883e+00]
 ...
 [-5.11920237e-02 -6.67271959e-02  6.47811344e-04 ...  9.56304104e-01
  -4.92595634e-01  9.65889347e-01]
 [ 6.11204008e+00  7.50472803e+00  7.17468111e-01 ...  3.00481509e+00
   1.25974457e+00  3.00025862e+00]
 [-5.11920237e-02  1.41661480e-01 -3.57762338e-01 ... -2.94365761e-01
  -4.92595634e-01 -2.89359777e-01]] 	 [[-5.11920237e-02  2.73569609e-03 -1.18822239e-01 ... -2.72802487e-01
   1.25974457e+00 -2.89359777e-01]
 [-4.26345282e-01 -1.36190088e-01 -7.16172488e-01 ... -8.55010872e-01
  -4.92595634e-01 -8.52057660e-01]
 [-6.40718573e-01 -4.83504548e-01 -5.96702438e-01 ... -8.11884325e-01
  -4.92595634e-01 -8.08773208e-01]
 ...
 [ 2.84284740e+00  4.88975940e-01  5.49627011e+00 ...  1.68945540e+00
   1.25974457e+00  1.68008281e+00]
 [ 1.09587944e-01  2.80587264e-01 -2.38292289e-01 ... -5.09998496e-01
  -4.92595634e-01 -5.05782040e-01]
 [ 1.71738762e+00  4.88975940e-01  2.98739906e+00 ...  1.04255720e+00
  -4.92595634e-01  1.05245825e+00]] 	 [[-0.80149854 -0.62243033 -0.71617249 ... -1.1568967  -0.49259563
  -1.15504883]
 [-0.6943119  -0.62243033 -0.47723239 ... -1.22158652 -0.49259563
  -1.21997551]
 [-0.80149854 -0.62243033 -0.71617249 ... -1.11377015 -0.49259563
  -1.11176438]
 ...
 [-0.58712525 -0.41404166 -0.59670244 ... -0.63937814 -0.49259563
  -0.6356354 ]
 [-0.58712525 -0.41404166 -0.59670244 ... -0.8334476  -0.49259563
  -0.83041543]
 [-0.74790522 -0.55296744 -0.71617249 ... -0.85501087 -0.49259563
  -0.85205766]]

In [37]:
from sklearn.decomposition import PCA

# keep the first two principal components of the data
pca = PCA(n_components = 3)

# transform data into the first two principal components
X_pca = pca.fit_transform(X_scaled)

print("Original shape: {}".format(str(X_scaled.shape)))
print("Reduced shape: {}".format(str(X_pca.shape)))

Original shape: (8760, 31)
Reduced shape: (8760, 3)

In [38]:
print(pca.explained_variance_ratio_)

[0.50486352 0.13677276 0.08887131]

In [40]:
0.50486352 + 0.13677276 + 0.08887131 * 100

9.52876728

In [41]:
total_var = pca.explained_variance_ratio_.sum() * 100
print(X_pca, total_var)

[[-3.64865781  0.08240973 -0.06856613]
 [-3.79158461  0.10060295  0.01068868]
 [-3.7546551   0.11984176  0.08803432]
 ...
 [-3.05358411  0.37848672 -0.10841563]
 [-3.22605934  0.13078587 -0.50051315]
 [-3.48900937  0.09397268  0.18617004]] 73.0507583782348